Repository sumi-0011/took, pull requests merged in 2022-05, with the labels that each got.

#38 testing
  App.tsx
  __tests__/App-test.js
  __tests__/__snapshots__/App-test.js.snap
  assetsTransformer.js
  jest.config.js
  package-lock.json
  package.json
  yarn.lock
Labels: 환경세팅

#36 Add relocation marker in TCRegisterScreen
  src/screens/TCRegister/TCRCategoryScreen.tsx
Labels: api연동

#41 Test/#40 jest config, 프로젝트 환경설정
  App.tsx
  __mocks__/@react-native-firebase/auth.js
  __mocks__/react-native-geolocation-service.js
  __tests__/App-test.js
  babel.config.js
  jest.config.js
  src/components/Camera/index.tsx
  src/components/CategoryCheckbox/index.tsx
  src/components/Header/index.tsx
  src/components/Profile/index.tsx
  src/navigations/AuthNavigation.tsx
  src/navigations/MainNavigation.tsx
  src/navigations/TCRegisterNavigation.tsx
  src/screens/Auth/LoginScreen.tsx
  src/screens/Auth/RegisterScreen.tsx
  src/screens/HomeScreen.tsx
  src/screens/MapScreen.tsx
  src/screens/TCRegister/CameraScreen.tsx
  src/screens/TCRegister/TCRCategoryScreen.tsx
  src/screens/TCRegister/TCRInfoScreen.tsx
  tsconfig.json
Labels: 환경세팅, 테스트

#51 feat : my page layout & base code line
  __tests__/__snapshots__/App-test.js.snap
  babel.config.js
  ios/Podfile.lock
  ios/took.xcworkspace/contents.xcworkspacedata
  package.json
  src/common/hooks/useAsyncStorageQuery.tsx
  src/common/hooks/useScrollFlatlist.tsx
  src/common/hooks/useScrollSync.tsx
  src/common/mocks/UserScreenMock.ts
  src/common/types/HeaderConfig.ts
  src/common/types/ScrollPair.ts
  src/common/types/TCInfo.ts
  src/common/types/UserInfo.ts
  src/common/types/Visibility.ts
  src/components/CollapsingHeader/index.tsx
  src/components/ConnectionList/index.tsx
  src/components/Profile/index.tsx
  src/components/TCCard/index.tsx
  src/components/TabBar/index.tsx
  src/images/defaultImg.png
  src/navigations/MainNavigation.tsx
  src/screens/User/UserScreen.tsx
  src/screens/UserScreen.tsx
  yarn.lock
Labels: 기능 개발, UI

#61 fix : map backbtn position fix
  android/app/src/main/AndroidManifest.xml
  src/screens/MapScreen.tsx
  src/screens/TCRegister/TCRCategoryScreen.tsx
Labels: fix

#50 MapScreen.test.js 작성
  __tests__/screens/MapScreen.test.js
Labels: 테스트
